export let  data=[
    {img:`https://assets.pharmeasy.in/apothecary/images/medicine_ff.webp?dim=256x0`,
      name:`Medicine`,
       off:`UP TO 20% OFF`},
       {img:`https://assets.pharmeasy.in/apothecary/images/labtest_ff.webp?dim=256x0`,
      name:`Lab Test`,
       off:`UP TO 70% OFF`},
       {img:`https://assets.pharmeasy.in/apothecary/images/healthcare_ff.webp?dim=256x0`,
      name:`Healthcare`,
       off:`UP TO 60% OFF`},
       {img:`https://assets.pharmeasy.in/apothecary/images/health_blogs_ff.webp?dim=256x0`,
      name:`Health Blogs`,
       },
       {img:`https://assets.pharmeasy.in/apothecary/images/plus_ff.webp?dim=256x0`,
      name:`Plus`,
       off:`SAVE 5% EXTRA`},
       {img:`https://assets.pharmeasy.in/apothecary/images/offers_ff.webp?dim=256x0`,
      name:`Offers`,
       off:``},
       {img:`https://assets.pharmeasy.in/apothecary/images/offers_1_ff.webp?dim=256x0`,
      name:`Surgeries`,
       off:``},
       {img:`https://assets.pharmeasy.in/apothecary/images/value_store.png?dim=256x0`,
      name:`Value Store`,
       off:`UP TO 50% OFF`}
]